extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-css-modules
  - stylelint-config-prettier
  - stylelint-config-prettier-scss
rules:
  no-empty-source:
    - true
    - severity: warning
  block-no-empty:
    - true
    - severity: warning
overrides:
  - files:
      - '**/*.module.scss'
      - '**/*.module.css'
    rules:
      selector-class-pattern:
        - '^[a-z][a-zA-Z0-9]+$'
        - message: Expected class selector in CSS module to be camelCase
